### ISSUE TITLE
can't import in android studio?

### ISSUE THREAD

**Issue by jimlee2** [enricocid/lffl-feed-reader#5]
hello
I can't import it to android studio because of the external libraries. Can you please give instruction on how to import all libraries?
for example
````
 * Project lffl2:H:\lffl-feed-reader-master\project.properties:
Library reference ..\Crouton could not be found
Path is H:\lffl-feed-reader-master\..\Crouton which resolves to H:\Crouton

````

**Comment by enricocid** [comment]
This project is for eclipse, not for AS. I still have to migrate the project (the real problem is that AS runs very slow on my pc... :( )

**Comment by jimlee2** [comment]
so there absolutely no way you can make it work on Android Studio? because that would be much easier

**Comment by enricocid** [comment]
I realize we should be using Android Studio by now but there's nothing I can do about that.
Unfortunately my PC (7 years old PC ) can't handle android studio , and I need AS in order to migrate my eclipse project to gradle
I've already tried to export it as a gradle project from eclipse but with no success ...

**Comment by enricocid** [comment]
@jimlee2 can You try to import the new master-as?
it should work
thanks
